### ISSUE TITLE
App not visible in New Relic ONE when locally served or published

### ISSUE THREAD

**Issue by xrismck** [newrelic/nr1-browser-analyzer#13]
I followed the steps provided for installation and am able to get the app built, published, deployed and subscribed to.

Here are my results with all apps I've tried to publish so far:
SUCCESSES:
nr1-cloud-optimize
nr1-container-explorer
nr1-customer-journey
nr1-datalyzer
nr1-groundskeeper
nr1-neon

FAILURES:
nr1-event-stream 
nr1-browser-analyzer            Issue:  https://github.com/newrelic/nr1-browser-analyzer/issues/13
nr1-top                         Issue:  https://github.com/newrelic/nr1-top/issues/9

---------------------------------------------------------------------------------------------

OUTPUT:   nr1 nerdpack:info --verbose

init version: @oclif/command@1.5.19 argv: [ '--verbose', [length]: 1 ]
Fetching info from registry...
Request: POST https://artifact-registry.service.newrelic.com/graphql
Data: 'query {\n                package(uuid: ' +
  '"a19f7cc1-918b-4c65-9d71-bc67320a044c") {\n               ' +
  '     uuid\n                    accountId\n                 ' +
  '   publications {\n                        createdAt\n     ' +
  '                   createdByUser\n                        ' +
  'version\n                    }\n                }\n         ' +
  '       packageDeployments(uuid: ' +
  '"a19f7cc1-918b-4c65-9d71-bc67320a044c") {\n               ' +
  '     channel\n                    deployedPublication {\n  ' +
  '                      version\n                    }\n     ' +
  '           }\n            }'
Headers: {
  'API-Key': '<my api key>',
  'Content-Type': 'application/graphql'
}

Registry: Present
Id: a19f7cc1-918b-4c65-9d71-bc67320a044c
Region: us
Account ID: 1847652
Local version: 0.1.6

Version   Date           Deployed to channel
0.1.6     3 minutes ago  DEV

---------------------------------------------------------------------------------------------
LOCAL SERVER EXECUTION
STEP:	Install
npm install

STEP:	Run locally
npm start

STEP:	Test
https://one.newrelic.com/?nerdpacks=local

RESULT:	App Not Displayed
---------------------------------------------------------------------------------------------
PUBLISH TO NEW RELIC ONE

STEP:	Create a new UUID
nr1 nerdpack:uuid -gf
GGenerated id is a19f7cc1-918b-4c65-9d71-bc67320a044c

STEP:	Force publish, override version if exists
nr1 nerdpack:publish -f 

STEP:	Deploy to DEV
nr1 nerdpack:deploy --channel=DEV

STEP:	Subscribe to DEV
nr1 nerdpack:subscribe --channel=DEV

STEP:	Check info
nr1 nerdpack:info --verbose

Version   Date           Deployed to channel
0.1.5     4 minutes ago  DEV

RESULT:  App Not Displayed
---------------------------------------------------------------------------------------------

What additional information should I provide to help with troubleshooting?

**Comment by tangollama** [comment]
This app shows up in the entity explorer when you select a browser entity. There is not a launcher for this app.

**Comment by Friss** [comment]
@tangollama Could the readme be updated with that? 

It just says visit the launcher page which doesn't show anything. I couldn't find this until I came across this issue.
