### ISSUE TITLE
Unable to use custom dates with this nerdpack

### ISSUE THREAD

**Issue by monitorjain** [newrelic/nr1-browser-analyzer#16]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )
## Description
The nerdpack throws errors when I use time picker for a custom date. Let's say I pick start time as Nov 5th 1.05 pm - Nov 5th 2.05 pm. The nerdpack throws an error which seems wrong because it complains start time must be before end time (which in this case it obviously is). 

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
Load Site/Browser Analyser and click time picker to select custom time
Pick start time as Nov 5th 1.05 pm or whichever date that suits
Pick end time as Nov 5th 2.05 pm or any date that suits
Note in this case, there is a 1 hour window selected.
Now, submit your time input and you would see an error render on the page
<img width="1680" alt="Screen Shot 2019-11-06 at 9 02 31 am" src="https://user-images.githubusercontent.com/45892212/68250719-9b9aab80-0075-11ea-9673-e0298df11b24.png">

## Expected Behaviour
[NOTE]: # ( Tell us what you expected to happen. )
I should see the customer sentiments breakdown for that time divided into 3 buckets (Satisfied, Tolerating and Frustrated, plus optimisation recommendations). 

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:   @datanerd/nr1/1.2.2 darwin-x64 node-v10.16.3
* Browser name and version: various (mostly Chrome, Firefox, Safari and IE)
* Operating System and version: Mac OS 10.14.6

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by tangollama** [comment]
We can address this with the nr1-community lib in a standard way.
